name: Unzip archive

on:
  push:
    paths:
      - 'CncAi_Modular (2).zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip archive
        run: |
          unzip 'CncAi_Modular (2).zip' -d extracted
          rm 'CncAi_Modular (2).zip'

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Unzipped archive and removed zip"
          git push
